flags:
  vita-cera:
    r2purs: True
extra-package-dbs: []
extra-deps:
  - servant-purescript-0.5.0.0
  - uuid-aeson-0.1.0.0
packages:
  - './vita-cera'
  - './vita-cera-client'
  - './bz'
  - './gjanajo'
  - location:
      git: https://github.com/lethom/auth-token.git
      commit: 51443df28771ea6b2fea457ca83872f6d23890b5
    subdirs:
      - servant-auth-token-api
      - servant-auth-token-server
      - auth-token
      - auth-token-persistent
      - token
      - token-persistent
      - token-random
      - token-aeson
resolver: lts-7.0
